# Generated by Django 5.1.6 on 2025-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_alter_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
