# Generated by Django 5.1.6 on 2025-02-11 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_stars', to='hotel_app.hotel'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
